# Site settings
baseURL = "http://cancermapproject.org/"
languageCode = "en-us"
title = "The CancerMap Project"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Menu
[menu]
  [[menu.main]]
    identifier = "project"
    name = "The Project"
    url = "/project"
    weight = 10

  [[menu.main]]
    identifier = "dataset1"
    name = "Dataset 1"
    url = "/dataset1"
    weight = 20

  [[menu.main]]
    identifier = "dataset2"
    name = "Dataset 2"
    url = "/dataset2"
    weight = 30

  [[menu.main]]
    identifier = "outlook"
    name = "Outlook"
    url = "/outlook"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 50

# Site parameters
[params]

    # Meta
    description = "Project Fund application for the CancerMap Project"
    author = "Florian Heigwer et al."
    keywords = "biology, computer vision, machine learning, drug discovery, high-content imaging, microscopy, bioinformatics, computational biology"

    # Back-to-top button name
    bttButton = ""
    favicon = "main_files/favicon.ico"  
